### ISSUE TITLE
Alphabetical order

### ISSUE THREAD

**Issue by quangphuc789** [uhub/awesome-javascript#2]
The libraries / frameworks should be organised in alphabetical order, and be stated in a standard SOP. Next time if anybody is going to update must follow this practice. Easier to read and search.

**Comment by ccding** [comment]
It was ordered by the number of stars.

**Comment by quangphuc789** [comment]
Okay thanks :)

**Comment by shrpne** [comment]
I think it's better to organize libraries by logical groups
